apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: secret-inject 
  namespace: aks-namespace   # name of namespace
spec:
  vault:
    name: kvnames # name of key vault - kvnames gets replaced with input variable
    object:
      name: ey-secret # name of the akv object
      type: secret # akv object type